export const ModalViewsType = {
    PRODUCT_ADD_VIEW : 'PRODUCT_ADD_VIEW',
    PRODUCT_UPDATE_VIEW : 'PRODUCT_UPDATE_VIEW',
    CATEGORY_ADD_VIEW : 'CATEGORY_ADD_VIEW',
    CATEGORY_UPDATE_VIEW : 'CATEGORY_UPDATE_VIEW',
    USER_ORDERS_VIEW : 'USER_ORDERS_VIEW',
    OPTION_ADD_VIEW : 'OPTION_ADD_VIEW',
    BLOG_CATEGORY_ADD_VIEW : 'BLOG_CATEGORY_ADD_VIEW',
    BLOG_CATEGORY_UPDATE_VIEW : 'BLOG_CATEGORY_UPDATE_VIEW',
    BLOG_POST_ADD_VIEW : 'BLOG_POST_ADD_VIEW',
    BLOG_POST_UPDATE_VIEW : 'BLOG_POST_UPDATE_VIEW',
    HOME_MAIN_SLIDER_VIEW : 'HOME_MAIN_SLIDER_VIEW',
    HOME_MAIN_BANNER_GRID_VIEW : 'HOME_MAIN_BANNER_GRID_VIEW',
}
