export const ModalViewsType = {
    PRODUCT_ADD_VIEW : 'PRODUCT_ADD_VIEW',
    PRODUCT_UPDATE_VIEW : 'PRODUCT_UPDATE_VIEW',
    CATEGORY_ADD_VIEW : 'CATEGORY_ADD_VIEW',
    CATEGORY_UPDATE_VIEW : 'CATEGORY_UPDATE_VIEW',
}
