export const sliderTypes = {
    MULTIPLE_SLIDER : 'MULTIPLE_SLIDER',
    DOUBLE_SLIDER : 'DOUBLE_SLIDER',
    SIMPLE : 'SIMPLE',
}

export default {
    // SLIDER : 'SLIDER',
    // DOUBLE_SLIDER : 'DOUBLE_SLIDER',
    // BLOG_SLIDER : 'BLOG_SLIDER',
    POPULAR_CATEGORIES: 'POPULAR_CATEGORIES',
    TRIPLE_BANNER: 'TRIPLE_BANNER',
    BRANDS_BANNER: 'BRANDS_BANNER',
    SINGLE_BANNER: 'SINGLE_BANNER',
    BLOG_SLIDER : 'BLOG_SLIDER',
    ...sliderTypes
}
